serviceName: base_service
development: true
database:
  readDb:
    connectionString: root:admin@tcp(localhost:3306)/baseservices?tls=skip-verify&autocommit=true
    dbType: mysql
    migrationFilePath: migrations
  writeDb:
    connectionString: root:admin@tcp(localhost:3307)/baseservices?tls=skip-verify&autocommit=true
    dbType: mysql
    migrationFilePath: migrations
http:
  port: :5001
  development: true
  shutdownTimeout: 15
  resources: ["internal/resources/en.json",	"internal/resources/fr.json",	"internal/resources/vi.json"]
  rateLimiting:
    rateFormat: "100000-H"
grpc:
  port: :5002
  development: true
  maxConnectionIdle: 5
  timeout: 15
  maxConnectionAge: 5
  time: 10
logger:
  level: debug
  devMode: false
  encoder: json
tracing:
  enable: true
  serviceName: base_service
  hostPort: "localhost:4317"
  logSpans: false
  apiKey: be2b6c37a20b98b8815412b3fe3bb166e7d0NRAL
kafka:
  dialer:
    username: AGLMKA433JNXALY3
    password: 8hG3ZfwlT77+8dNLSMMOB+Is0JXAGYCTH9fPm+FzzyYlZvuChC4rD50GrwXo/CXF
  config:
    brokers: ["pkc-ldvr1.asia-southeast1.gcp.confluent.cloud:9092"]
    groupID: base_service_consumer
    initTopics: true
    numWorker: 20
  topics:
    userUpdate:
      topicName: user_update
      numPartitions: 2
      replicationFactor: 1
    userUpdated:
      topicName: user_updated
      numPartitions: 2
      replicationFactor: 1
redis:
  addrs: ["localhost:6379"]
  password: ""
  db: 0
  poolSize: 300
heathcheck:
  interval: 100000
  port: :6001
  goroutineThreshold: 50
metrics:
  prometheusPath: /metrics
  prometheusPort: :8001
