serviceName: base_service
development: false
database:
  readDb: 
    connectionString: VAULT_DATA
    dbType: mysql
    migrationFilePath: migrations
  writeDb: 
    connectionString: VAULT_DATA
    dbType: mysql
    migrationFilePath: migrations
http:
  port: :5000
  development: false
  shutdownTimeout: 15
  resources: ["internal/resources/en.json",	"internal/resources/fr.json",	"internal/resources/vi.json"]
  rateLimiting:
    rateFormat: "100-S"
grpc:
  port: :5001
  development: false
  maxConnectionIdle: 5
  timeout: 15
  maxConnectionAge: 5
  time: 10
logger:
  level: info
  devMode: false
  encoder: json
jaeger:
  enable: true
  serviceName: base_service
  hostPort: VAULT_DATA
  logSpans: false
kafka:
  config:
    brokers: VAULT_DATA
    groupID: base_service_consumer
    initTopics: false
    numWorker: 20
  topics:    
    userUpdate:
      topicName: user_update
      numPartitions: 10
      replicationFactor: 1    
    userUpdated:
      topicName: s14e.base_service.user_updated
      numPartitions: 10
      replicationFactor: 1
redis:
  addrs: VAULT_DATA
  password: ""
  db: 0
  poolSize: 300
heathcheck:
  interval: 10
  port: :6001
  goroutineThreshold: 100
metrics:
  prometheusPath: /metrics
  prometheusPort: :8001
vault:
  address: "https://vault.dev.tiki.services/"
  path: "kv/data/k8s/dev/s14e/baseservice/"
  role: "default"
  mountPoint: "s14e"

